### ISSUE TITLE
Crash Type 'Language is not appearing properly' is confusing

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/oi-fenix-campaign#2]
IMHO 'Language is not appearing properly' is confusing. It's supposed to indicate that localization is off, however this could be misunderstood by users.

@couci can we come up with another better name?

**Comment by LucyeoH-zz** [comment]
Suggested alternatives - "Localization issues reported - we've had reports that this language is not displaying correctly.", "Localization issue - this may not be appearing correctly in your language".  "Language display issues" "Translation Error" "Localization Error"

**Comment by couci** [comment]
I like the "Localization issue - this may not be appearing correctly in your language" since it makes it clear on what we are asking for.
@MichaelKohler what do you think?

**Comment by MichaelKohler** [comment]
Seems a bit long, but I can check how it would look inside the select element in Fenix.

Quick suggestion, can we change to "Localization issue - not appearing correctly in your language"?

**Comment by LucyeoH-zz** [comment]
Feel free to take any portion of these that is appropriate. I'm not sure
where exactly this would appear. Could say "Localization Issue - Text may
not appear correctly in your language"
