### ISSUE TITLE
Replace Webcompat link with button?

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/oi-fenix-campaign#3]
We have the follow paragraph in the form:

```
The website you’re visiting has a bug in Firefox but not in another browser? File your bug here.
```

@freaktechnik came up with the idea to add a button instead of a link, to give this a bit more visibility

I agree with that, as I'd expect quite some issues with webcompat and I suppose we don't wanna triage from our repo into the webcompat repo manually.

@couci thoughts?

**Comment by couci** [comment]
what worries me here is that people that won't read  this properly will click on the button by mistake. To be honest I prefer that those issues end up on us and then we send them to the webcompat team rather the other way around
