### ISSUE TITLE
Hosting Questions

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/oi-fenix-campaign#4]
- [x] Hosting could be done through ParSys? I have a k8s config, or we could run the Docker container as is
- [x] We will need a nice subdomain. This will need to go through Parsys as well as I guess we want a *.mozilla.community domain?

**Comment by couci** [comment]
let's aim for bughunterissues.mozilla.community @hmitsch where should we open a request for this?

**Comment by hmitsch** [comment]
I adapted the Google Analytics configuration.

@couci can you talk to @johngian to get answers to your questions?

**Comment by couci** [comment]
by talking with @johngian he said the best most vaiable option is hosting this via heroku (like we did on the dark funnel campaign). 
@hmitsch how we can ensure that @MichaelKohler gets an account there? As far as I understand it's sso supported

**Comment by hmitsch** [comment]
Unfortunately, I have to defer to @johngian again. He is the most knowledgeable Heroku person in the OI team.

My best guess/pointer is to take a look at this access group and the links provided on it: https://mozillians.org/group/heroku-members/

Best regards,
   Henrik

**Comment by MichaelKohler** [comment]
Deployed to https://oi-fenix-campaign-reporting.herokuapp.com

**Comment by johngian** [comment]
@MichaelKohler Let's take it offline so we can migrate to mozilla heroku account

**Comment by johngian** [comment]
Ok, heroku app ownership is now under mozilla org

**Comment by johngian** [comment]
@MichaelKohler should i change the DNS or you need to configure anything on the backend before i switch ?

**Comment by MichaelKohler** [comment]
Go for it, I don't use the URL in the backend, so we're independent there.

**Comment by johngian** [comment]
Changed DNS. HTTPS will also be applied automatically.

**Comment by MichaelKohler** [comment]
Thanks nemo, all working :)

**Comment by ZackBoe** [comment]
Although `bughunterissues.mozilla.community` is available over HTTPS, it does not currently redirect from HTTP. The "Step 2: Give all details" link on [Become a Beta Testing BugHunter](https://events.mozilla.org/becomeabetatestingbughunter) uses the HTTP URL.


(Hopefully this repo is the right place to report this!)

**Comment by MichaelKohler** [comment]
@ZackBoe yes it is, thanks!

@johngian could you add an automatic redirect to https?

**Comment by MichaelKohler** [comment]
oh, nevermind, we don't have a proxy here, and Heroku doesn't seem to be able to do it.. guess I'll need to do it in code: https://help.heroku.com/J2R1S4T8/can-heroku-force-an-application-to-use-ssl-tls

I'll tell Konstantina to fix the link so at least that points to https for now.

**Comment by MichaelKohler** [comment]
It's now redirecting to HTTPS if called through HTTP.
