### ISSUE TITLE
Form Feedback: Update description under "Device"

### ISSUE THREAD

**Issue by bbinto** [mozilla/oi-fenix-campaign#8]
I'd love to suggest to add the grey text from
"What Android device are you using?"

to
"What Android device are you using? (e.g. Samsung S10, Google Pixel 2, Motorola G7)"

**Comment by MichaelKohler** [comment]
Yes, that's a good idea. Thanks!

**Comment by MichaelKohler** [comment]
due to the limited horizontal space on a mobile phone I've made a change to the label as well as the placeholder to convey this example
